spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update} # Parameterized for production usage
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Security / JWT Keys
app:
  cors:
    allowedOrigins: ${ALLOWED_ORIGIN:http://localhost:5173,http://localhost:3000}
  jwt:
    secret: ${JWT_SECRET}
    expirationMs: 86400000 # 24 Hours

server:
  port: 8080
